"""user profile

Revision ID: 34013565bda4
Revises: None
Create Date: 2013-04-13 14:30:47.554221

"""

# revision identifiers, used by Alembic.
revision = '34013565bda4'
down_revision = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_id')
    ### end Alembic commands ###
